name: Black-n-lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
      - name: Lint with flake8
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        run: |
          if [ -f flake8-requirements.txt ]; then pip install -r flake8-requirements.txt; fi
          # stop the build if there are Python syntax errors or undefined names
          flake8 --config .flake8
